name: Ping Telegram Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # каждые 5 минут
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call bot webhook
        run: |
          curl -X POST https://telegram-server-3cyz.onrender.com/cron
